### ISSUE TITLE
Can`t update sources.list file

### ISSUE THREAD

**Issue by MikeVL** [example42/puppet-apt#14]
I`m use this config:

```puppet
    class { 'apt':
        source_dir => 'puppet:///modules/mymodule/apt',
    }
```
In path /modules/mymodule/apt i have two files: apt.conf and sources.list, but files in /etc/apt are empty.

**Comment by tuxmea** [comment]
@MikeVL does the fix from @sathieu solve your problem?

**Comment by MikeVL** [comment]
Currently I do not use Puppet
