### ISSUE TITLE
Repository class should allow specifying keyserver

### ISSUE THREAD

**Issue by yannh** [example42/puppet-apt#28]
Creating a repo with a key always calls apt::key without passing a keyserver parameter, so defaulting to subkeys.pgp.net, which has been super unreliable lately. I believe we should be able to pass a keyserver to the repository?

**Comment by tuxmea** [comment]
@yannh any update on this? Do you need help with a PR?

**Comment by yannh** [comment]
Hi @tuxmea , I think I did back at the time and it got merged, check the history of the repository.pp file: https://github.com/example42/puppet-apt/commits/master/manifests/repository.pp , so this ticket should have been closed long ago? Thanks!

**Comment by tuxmea** [comment]
Closing ticket according to last comment.
