### ISSUE TITLE
apt::dater: Lack of support for apt-dater 1.0.2+ XML configuration files

### ISSUE THREAD

**Issue by gertvdijk** [example42/puppet-apt#55]
For some reason the author of apt-dater decided to [change the configuration format of the management host to XML structures](https://github.com/DE-IBH/apt-dater/commit/3a84efadc2f969bcc4865d57f0515d86c4d24567) in a minor update (1.0.2 -- [changelog](https://github.com/DE-IBH/apt-dater/commit/794a62961674ea3cd17acd2c602060c0b5bd3c25)), resulting in backwards incompatible generated hosts.conf files.

This breaks apt-dater for the latest Ubuntu release 15.04 which incorporates a 1.0.1 version with some extra commits introducing the XML configuration format.

```
gert@host:~$ apt-dater
** Message: Creating default config file /home/gert/.config/apt-dater/apt-dater.xml
** Message: Creating default config file /home/gert/.config/apt-dater/hosts.xml
** Message: Creating default config file /home/gert/.config/apt-dater/screenrc
```

It took me some time to find out why all of this stuff broke down after the Ubuntu 15.04 upgrade and I was surprised to find out this backwards incompatible change in a minor apt-dater release and Debian/Ubuntu having backported it to 1.0.1 as well.

FYI - submitted Ubuntu bug report too: [1451002](https://bugs.launchpad.net/ubuntu/+source/apt-dater/+bug/1451002).

**Comment by sathieu** [comment]
Note: this doesn't affect jessie which has version 0.9.0.

Any PR appreciated.
