### ISSUE TITLE
Unattended-Upgrade, is it removed or replaced?

### ISSUE THREAD

**Issue by femans** [example42/puppet-apt#57]
in version 1.8 there was support for unattended-upgrades, including a function for remove-unused-dependencies.
Now I can´t find it back and our service doesn´t do this anymore. 
What happened to it? 
Regards, F

**Comment by sathieu** [comment]
Do you mean apt::unattended_upgrade_automatic? It's still here!

**Comment by femans** [comment]
and remove_unused_dependencies? This is automation for: apt-get autoremove

**Comment by sathieu** [comment]
It's called automaticremove now.

**Comment by femans** [comment]
Thanks!

**Comment by sathieu** [comment]
Closing.
