### ISSUE TITLE
apt::dater: Parameter path failed on File[undef]

### ISSUE THREAD

**Issue by e-it** [example42/puppet-apt#66]
Hello,

I tried to use the module but on deploying I'm getting the error

> Error: Failed to apply catalog: Parameter path failed on File[undef]: File paths must be fully qualified, not 'undef' at /etc/puppet/modules/apt/manifests/dater/manager.pp:36

This is my definition:

```
node 'puppet' {
class { 'apt::dater':
role => 'manager',
manager_ssh_key => template('site/apt-dater.priv.key');
}
```

**Comment by alvagante** [comment]
Are you using future parser / Puppet 4 ?

**Comment by SPQRInc** [comment]
No, it's puppet 3.8.

**Comment by sathieu** [comment]
Yes: $manager_home_dir and $manager_home_conf_dir are mixed up. Do they need to be the same var?

NB: I use my own module for apt_dater, and don't have time to move currently.

**Comment by SPQRInc** [comment]
So I have to change it in the module? When I'm done with that: How can I export the host to the manager?
