### ISSUE TITLE
subkeys.pgp.net not responding?

### ISSUE THREAD

**Issue by craigcarnell** [example42/puppet-apt#69]

**Comment by alvagante** [comment]
Maybe a temporary issue with the server?

**Comment by craigcarnell** [comment]
@alvagante It's been going on for quite some time

**Comment by alvagante** [comment]
@craigcarnell Any suggestion for an alternative reliable one? (Are keys on these servers somehow synced ? I'm not so expert in the field)

**Comment by craigcarnell** [comment]
@alvagante keyserver.ubuntu.com

**Comment by alvagante** [comment]
Changed the default keyserver value, thanks.
